#!/bin/bash
set -x
#telegram token
TG_TOKEN="1111111111:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
TG_CHAT_ID="1111111111"
TG_API="https://api.telegram.org/bot"
#bark token
BARK_TOKEN="xxxxxxxxxxxxxxxxxxxxxx"
#wechat/wecom id and token
WECOM_ID="xxxxxxxxxxxxxxxxxx"
WECOM_SECRET="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
WECOM_AGENT_ID="1111111"
WECOM_TO_USER="xxxxxx"

CURL_ARGS="--silent --location"

#set default title and msg
title=${1:-$(hostname)}
msg=${2:-$(basename "$(pwd)")}
channel=${3:-t}

#telegram
if [[ $channel == *"t"* ]]; then
  curl -X POST "$TG_API$TG_TOKEN/sendMessage" \
    -d "text=<b>$title</b>%0A$msg" \
    -d "chat_id=$TG_CHAT_ID" \
    -d "parse_mode=HTML" \
    $CURL_ARGS >>/dev/null 2>&1 &
fi

#bark
if [[ $channel == *"b"* ]]; then
  curl -X POST "https://api.day.app/$BARK_TOKEN" \
    --data-urlencode "title=$title" \
    --data-urlencode "body=$msg" \
    $CURL_ARGS >>/dev/null 2>&1 &
fi

#wechat
if [[ $channel == *"w"* ]]; then
  tmp_token=$(curl "https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=${WECOM_ID}&corpsecret=${WECOM_SECRET}" -s | sed 's/.*access_token":"\([^"]*\)".*/\1/g')
  t=${title//\"/\\\"/}
  m=${msg//\"/\\\"/}
  curl -X "POST" "https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=$tmp_token" -H "Content-Type: text/plain; charset=utf-8" \
    -d "{ \"touser\": \"${WECOM_TO_USER}\", \"msgtype\": \"text\", \"agentid\": \"${WECOM_AGENT_ID}\", \"text\": { \"content\": \"${t}\n${m}\" } }" $CURL_ARGS >>/dev/null 2>&1 &
fi