#!/bin/bash
#set -x
#usage bark title msg channel(b|t|w|f|d)
#defualt title is hostname; default msg is current dir; default channel is telegram
#                     b for bark
#                     t for telegram (default)
#                     w for wechat/wecom
#                     f for feishu/lark
#                     d for discord
#eg `bark hello test btwfd` will send "hello\ntest" to all channel

#set default title msg and channel
title=${1:-$(hostname)}
msg=${2:-$(basename "$(pwd)")}
channel=${3:-t}

#telegram token
TG_TOKEN="1111111111:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
TG_CHAT_ID="1111111111"
TG_API="https://api.telegram.org/bot"
#bark token
BARK_TOKEN="xxxxxxxxxxxxxxxxxxxxxx"
#wechat/wecom id and token
WECOM_ID="xxxxxxxxxxxxxxxxxx"
WECOM_SECRET="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
WECOM_AGENT_ID="1111111"
WECOM_TO_USER="xxxxxx"
#feishu/lark webhook
FEISHU_WEB_HOOK_TOKEN="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
#discord webhook
DISCORD_WEBHOOK="https://discord.com/api/webhooks/xxxx"

CURL_ARGS="--silent --location"

#telegram
if [[ $channel == *"t"* ]]; then
  curl -X POST "$TG_API$TG_TOKEN/sendMessage" \
    -d "text=<b>$title</b>%0A$msg" \
    -d "chat_id=$TG_CHAT_ID" \
    -d "parse_mode=HTML" \
    $CURL_ARGS >>/dev/null 2>&1 &
fi

#bark
if [[ $channel == *"b"* ]]; then
  curl -X POST "https://api.day.app/$BARK_TOKEN" \
    --data-urlencode "title=$title" \
    --data-urlencode "body=$msg" \
    $CURL_ARGS >>/dev/null 2>&1 &
fi

#wechat
if [[ $channel == *"w"* ]]; then
  tmp_token=$(curl "https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=${WECOM_ID}&corpsecret=${WECOM_SECRET}" -s | sed 's/.*access_token":"\([^"]*\)".*/\1/g')
  t=${title//\"/\\\"/}
  m=${msg//\"/\\\"/}
  curl -X "POST" "https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=$tmp_token" -H "Content-Type: text/plain; charset=utf-8" \
    -d "{ \"touser\": \"${WECOM_TO_USER}\", \"msgtype\": \"text\", \"agentid\": \"${WECOM_AGENT_ID}\", \"text\": { \"content\": \"${t}\n${m}\" } }" $CURL_ARGS >>/dev/null 2>&1 &
fi

#feishu/lark
if [[ $channel == *"f"* ]]; then
  t=${title//\"/\\\"/}
  m=${msg//\"/\\\"/}
  notify_url="https://open.feishu.cn/open-apis/bot/v2/hook/$FEISHU_WEB_HOOK_TOKEN"
  curl -X "POST" "$notify_url" -H "Content-Type: application/json" -d '{ "msg_type": "post", "content": { "post": { "zh_cn": { "title": "'"$t"'", "content": [[{ "tag": "text", "text": "'"$m"'" }]] } } } }' \
  $CURL_ARGS >>/dev/null 2>&1 &
fi

#discord
if [[ $channel == *"d"* ]]; then
  curl -X "POST" $DISCORD_WEBHOOK -H "Content-Type: application/json" -d '{ "content": "'"$title\n$msg"'" }' \
  $CURL_ARGS >>/dev/null 2>&1 &
fi